server:
  tomcat:
    uri-encoding: UTF-8
    remote-ip-header: x-forwarded-for
  use-forward-headers: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

spring:
  boot:
    admin:
      client:
        username: ${management.security.user.name}
        password: ${management.security.user.password}
        read-timeout: 10000
        connect-timeout: 10000
        # url: http://localhost:8010
        instance:
          prefer-ip: true
          # name: ${spring.application.name}
          # management-base-url: http://${spring.cloud.client.ip-address}:${server.port}
          # service-base-url: http://${spring.cloud.client.ip-address}:${server.port}

  datasource:
    druid:
      connection-init-sqls: set names utf8mb4;
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&useSSL=false&autoReconnect=true
    username: alipay
    password: alipay
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    # 初始化大小，最小，最大
    initialSize: 1
    minIdle: 10
    maxActive: 200
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # Druid WebStatFilter配置
    web-stat-filter:
      enabled: true
      url-pattern: /*
      exclusions: '*.gif,*.png,*.jpg,*.html,*.js,*.css,*.ico,/druid/*'
    # Druid StatViewServlet配置
    stat-view-servlet:
      enabled: true
      url-pattern: /druid/*
      reset-enable: true
      login-username: admin
      login-password: admin
    # 配置日志输出
    filter:
      slf4j:
        enabled: true
        statement-create-after-log-enabled: false
        statement-close-after-log-enabled: false
        result-set-open-after-log-enabled: false
        result-set-close-after-log-enabled: false

  db:
    test_db:
      druid:
            connection-init-sqls: set names utf8mb4;
      url: jdbc:mysql://localhost:3306/test_db?useUnicode=true&useSSL=false&autoReconnect=true
      username: alipay
      password: alipay
      driver-class-name: com.mysql.jdbc.Driver
      platform: mysql
      type: com.alibaba.druid.pool.DruidDataSource

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

ribbon:
  eager-load:
    enabled: true
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  OkToRetryOnAllOperations: false
  ConnectTimeout: 60000
  ReadTimeout: 20000
  eureka:
    enable: true

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 20000
pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  pageSizeZero: true
  params: count=countSql